#!/usr/bin/env bash
set -euo pipefail

ROOT="$(cd "$(dirname "$0")" && pwd)"
LOG_PATH="${1:-${ROOT}/logs/windows_b07_gate.simulated.log}"
LOG_BASE="$(basename "${LOG_PATH}")"
SUMMARY_JSON_SENTINEL="${LOG_PATH%.log}.summary-json.missing"

print_usage() {
  echo "Usage: $0 [simulated-log-path]"
  echo "Default log: ${ROOT}/logs/windows_b07_gate.simulated.log"
  echo "Note: writing windows_b07_gate.log is blocked by design."
}

if [[ "${LOG_PATH}" == "-h" || "${LOG_PATH}" == "--help" ]]; then
  print_usage
  exit 0
fi

if [[ "${LOG_BASE}" == "windows_b07_gate.log" ]]; then
  echo "[SIMULATE] Refuse target: ${LOG_PATH}"
  echo "[SIMULATE] windows_b07_gate.log is reserved for real Windows evidence only."
  exit 2
fi

if [[ "${LOG_BASE}" != *.simulated.log ]]; then
  echo "[SIMULATE] Refuse target: ${LOG_PATH}"
  echo "[SIMULATE] simulated output file name must end with .simulated.log"
  exit 2
fi

mkdir -p "$(dirname "${LOG_PATH}")"

cat > "${LOG_PATH}" <<EOM
[B07] Windows evidence capture
[SIMULATE] Generated by simulate_windows_b07_evidence.sh (do not treat as real Windows evidence)
[B07] Source: collect_windows_b07_evidence.bat
[B07] HostOS: Windows_NT
[B07] CmdVer: Microsoft Windows [Version 10.0.22631.0]
[B07] Started: $(date '+%Y/%m/%d %H:%M:%S.00')
[B07] Working dir: C:\simd\tests\fafafa.core.simd\
[B07] Command: buildOrTest.bat gate
[B07] GateSummaryJson: ${SUMMARY_JSON_SENTINEL}

[GATE] 1/7 Build + check SIMD module
[GATE] 2/7 SIMD list suites
[GATE] 3/7 SIMD AVX2 fallback suite
[GATE] 4/7 CPUInfo portable suites
[GATE] 5/7 CPUInfo x86 suites
[GATE] 6/7 Windows public ABI smoke
[GATE] 7/7 Filtered run_all chain
[GATE] OK

[B07] GATE_EXIT_CODE=0

[B07] run_all summary snapshot
Total:  5
Passed: 5
Failed: 0
[B07] Total: 5
[B07] Passed: 5
[B07] Failed: 0
EOM

echo "[SIMULATE] OK: ${LOG_PATH}"
