#!/usr/bin/env python3
"""
simdgen - SIMD dispatch code generator for fafafa.core.simd

Generates Pascal include files from JSON operation definitions.
Zero external dependencies (uses only Python stdlib).

Usage:
    python3 tools/simdgen/simdgen.py [--verify] [--dry-run]

Options:
    --verify   Compare generated output against existing code (audit mode)
    --dry-run  Print what would be generated without writing files
"""

import json
import os
import sys
from pathlib import Path
from dataclasses import dataclass, field
from typing import Optional

SCRIPT_DIR = Path(__file__).parent
PROJECT_ROOT = SCRIPT_DIR.parent.parent
OPS_DIR = SCRIPT_DIR / "ops"
OUTPUT_DIR = PROJECT_ROOT / "src" / "generated"

HEADER = """\
{{
  This file is AUTO-GENERATED by tools/simdgen/simdgen.py
  DO NOT EDIT MANUALLY - changes will be overwritten.

  Source definitions: tools/simdgen/ops/
  Regenerate: python3 tools/simdgen/simdgen.py
}}
"""


# =============================================================================
# Data model
# =============================================================================

@dataclass
class TypeInfo:
    name: str
    vec_type: str
    scalar_type: str
    field_name: str
    lanes: int
    width: int
    mask_type: str
    ptr_type: str
    category: str
    decompose: Optional[list] = None


@dataclass
class Operation:
    name: str
    signature: str
    scalar_op: str
    doc: str
    applies_to: list
    scalar_body: Optional[str] = None
    category: str = ""


@dataclass
class SlotEntry:
    """A single dispatch table slot = operation + type"""
    op: Operation
    type_info: TypeInfo

    @property
    def dispatch_field(self) -> str:
        return f"{self.op.name}{self.type_info.name}"

    @property
    def facade_name(self) -> str:
        return f"Vec{self.type_info.name}{self.op.name}"

    @property
    def scalar_name(self) -> str:
        return f"Scalar{self.op.name}{self.type_info.name}"


# =============================================================================
# Registry: load types and operations from JSON
# =============================================================================

class Registry:
    def __init__(self):
        self.types: dict[str, TypeInfo] = {}
        self.operations: list[Operation] = []
        self.slots: list[SlotEntry] = []

    def load_types(self, path: Path):
        with open(path) as f:
            data = json.load(f)
        for name, info in data.get("types", {}).items():
            if name.startswith("_") or name == "PLACEHOLDER_MORE_TYPES":
                continue
            self.types[name] = TypeInfo(
                name=name,
                vec_type=info["vec_type"],
                scalar_type=info["scalar_type"],
                field_name=info["field"],
                lanes=info["lanes"],
                width=info["width"],
                mask_type=info["mask"],
                ptr_type=info["ptr"],
                category=info["category"],
                decompose=info.get("decompose"),
            )

    def load_operations(self, path: Path):
        with open(path) as f:
            data = json.load(f)
        category = data.get("category", "")
        for op_def in data.get("operations", []):
            op = Operation(
                name=op_def["name"],
                signature=op_def["signature"],
                scalar_op=op_def.get("scalar_op", ""),
                doc=op_def.get("doc", ""),
                applies_to=op_def.get("applies_to", []),
                scalar_body=op_def.get("scalar_body"),
                category=category,
            )
            self.operations.append(op)

    def build_slots(self):
        self.slots = []
        for op in self.operations:
            for type_name in op.applies_to:
                if type_name in self.types:
                    self.slots.append(SlotEntry(op=op, type_info=self.types[type_name]))

    def load_all(self):
        self.load_types(OPS_DIR / "types.json")
        for f in sorted(OPS_DIR.glob("*.json")):
            if f.name == "types.json":
                continue
            self.load_operations(f)
        self.build_slots()


# =============================================================================
# Code generators
# =============================================================================

def gen_signature(slot: SlotEntry) -> str:
    """Generate the function pointer type signature for a dispatch slot."""
    t = slot.type_info
    sig = slot.op.signature

    if sig == "binary":
        return f"function(const a, b: {t.vec_type}): {t.vec_type}"
    elif sig == "unary":
        return f"function(const a: {t.vec_type}): {t.vec_type}"
    elif sig == "compare":
        return f"function(const a, b: {t.vec_type}): {t.mask_type}"
    elif sig == "reduce":
        return f"function(const a: {t.vec_type}): {t.scalar_type}"
    elif sig == "load":
        return f"function(p: {t.ptr_type}): {t.vec_type}"
    elif sig == "store":
        return f"procedure(p: {t.ptr_type}; const a: {t.vec_type})"
    elif sig == "splat":
        return f"function(value: {t.scalar_type}): {t.vec_type}"
    elif sig == "zero":
        return f"function: {t.vec_type}"
    elif sig == "shift":
        return f"function(const a: {t.vec_type}; count: Integer): {t.vec_type}"
    elif sig == "ternary":
        return f"function(const a, b, c: {t.vec_type}): {t.vec_type}"
    else:
        return f"{{unknown signature: {sig}}}"


def generate_dispatch_slots(registry: Registry) -> str:
    lines = [HEADER, "{ Dispatch table slots }", ""]
    current_category = ""
    for slot in registry.slots:
        if slot.op.category != current_category:
            current_category = slot.op.category
            lines.append(f"    {{ --- {current_category} --- }}")
        sig = gen_signature(slot)
        lines.append(f"    {slot.dispatch_field}: {sig};")
    return "\n".join(lines) + "\n"


def generate_scalar_decl(registry: Registry) -> str:
    lines = [HEADER, "{ Scalar implementation declarations }", ""]
    for slot in registry.slots:
        t = slot.type_info
        sig = slot.op.signature
        if sig == "binary":
            lines.append(
                f"function {slot.scalar_name}(const a, b: {t.vec_type}): {t.vec_type};"
            )
        elif sig == "unary":
            lines.append(
                f"function {slot.scalar_name}(const a: {t.vec_type}): {t.vec_type};"
            )
        elif sig == "compare":
            lines.append(
                f"function {slot.scalar_name}(const a, b: {t.vec_type}): {t.mask_type};"
            )
        elif sig == "reduce":
            lines.append(
                f"function {slot.scalar_name}(const a: {t.vec_type}): {t.scalar_type};"
            )
        elif sig == "shift":
            lines.append(
                f"function {slot.scalar_name}(const a: {t.vec_type}; count: Integer): {t.vec_type};"
            )
        elif sig == "load":
            lines.append(
                f"function {slot.scalar_name}(p: {t.ptr_type}): {t.vec_type};"
            )
        elif sig == "store":
            lines.append(
                f"procedure {slot.scalar_name}(p: {t.ptr_type}; const a: {t.vec_type});"
            )
        elif sig == "splat":
            lines.append(
                f"function {slot.scalar_name}(value: {t.scalar_type}): {t.vec_type};"
            )
        elif sig == "zero":
            lines.append(
                f"function {slot.scalar_name}: {t.vec_type};"
            )
    return "\n".join(lines) + "\n"


def generate_scalar_impl(registry: Registry) -> str:
    lines = [HEADER, "{ Scalar implementation bodies }", ""]
    for slot in registry.slots:
        t = slot.type_info
        sig = slot.op.signature
        op = slot.op

        if sig == "binary":
            lines.append(f"function {slot.scalar_name}(const a, b: {t.vec_type}): {t.vec_type};")
            lines.append("var i: Integer;")
            lines.append("begin")
            if op.scalar_body:
                body = op.scalar_body.replace("{field}", t.field_name)
                lines.append(f"  for i := 0 to {t.lanes - 1} do")
                lines.append(f"    {body};")
            elif op.scalar_op in ("+", "-", "*", "/"):
                lines.append(f"  for i := 0 to {t.lanes - 1} do")
                lines.append(
                    f"    Result.{t.field_name}[i] := a.{t.field_name}[i] "
                    f"{op.scalar_op} b.{t.field_name}[i];"
                )
            else:
                lines.append(f"  // TODO: implement scalar {op.name} for {t.name}")
                lines.append(f"  Result := a;")
            lines.append("end;")
            lines.append("")

        elif sig == "unary":
            lines.append(f"function {slot.scalar_name}(const a: {t.vec_type}): {t.vec_type};")
            lines.append("var i: Integer;")
            lines.append("begin")
            if op.scalar_body:
                body = op.scalar_body.replace("{field}", t.field_name)
                lines.append(f"  for i := 0 to {t.lanes - 1} do")
                lines.append(f"    {body};")
            elif op.scalar_op == "not":
                lines.append(f"  for i := 0 to {t.lanes - 1} do")
                lines.append(f"    Result.{t.field_name}[i] := not a.{t.field_name}[i];")
            else:
                lines.append(f"  // TODO: implement scalar {op.name} for {t.name}")
                lines.append(f"  Result := a;")
            lines.append("end;")
            lines.append("")

        elif sig == "shift":
            lines.append(f"function {slot.scalar_name}(const a: {t.vec_type}; count: Integer): {t.vec_type};")
            lines.append("var i: Integer;")
            lines.append("begin")
            if op.scalar_body:
                body = op.scalar_body.replace("{field}", t.field_name)
                lines.append(f"  for i := 0 to {t.lanes - 1} do")
                lines.append(f"    {body};")
            elif op.scalar_op in ("shl", "shr"):
                lines.append(f"  for i := 0 to {t.lanes - 1} do")
                lines.append(f"    Result.{t.field_name}[i] := a.{t.field_name}[i] {op.scalar_op} count;")
            else:
                lines.append(f"  // TODO: implement scalar {op.name} for {t.name}")
                lines.append(f"  Result := a;")
            lines.append("end;")
            lines.append("")

        elif sig == "compare":
            lines.append(f"function {slot.scalar_name}(const a, b: {t.vec_type}): {t.mask_type};")
            lines.append("var i: Integer;")
            lines.append("begin")
            lines.append(f"  Result := 0;")
            lines.append(f"  for i := 0 to {t.lanes - 1} do")
            lines.append(f"    if a.{t.field_name}[i] {op.scalar_op} b.{t.field_name}[i] then")
            lines.append(f"      Result := Result or ({t.mask_type}(1) shl i);")
            lines.append("end;")
            lines.append("")

        elif sig == "reduce":
            lines.append(f"function {slot.scalar_name}(const a: {t.vec_type}): {t.scalar_type};")
            lines.append("var i: Integer;")
            lines.append("begin")
            if "Add" in op.name:
                lines.append(f"  Result := a.{t.field_name}[0];")
                lines.append(f"  for i := 1 to {t.lanes - 1} do")
                lines.append(f"    Result := Result + a.{t.field_name}[i];")
            elif "Min" in op.name:
                lines.append(f"  Result := a.{t.field_name}[0];")
                lines.append(f"  for i := 1 to {t.lanes - 1} do")
                lines.append(f"    if a.{t.field_name}[i] < Result then Result := a.{t.field_name}[i];")
            elif "Max" in op.name:
                lines.append(f"  Result := a.{t.field_name}[0];")
                lines.append(f"  for i := 1 to {t.lanes - 1} do")
                lines.append(f"    if a.{t.field_name}[i] > Result then Result := a.{t.field_name}[i];")
            elif "Mul" in op.name:
                lines.append(f"  Result := a.{t.field_name}[0];")
                lines.append(f"  for i := 1 to {t.lanes - 1} do")
                lines.append(f"    Result := Result * a.{t.field_name}[i];")
            else:
                lines.append(f"  // TODO: implement scalar {op.name} for {t.name}")
                lines.append(f"  Result := 0;")
            lines.append("end;")
            lines.append("")

        elif sig == "load":
            lines.append(f"function {slot.scalar_name}(p: {t.ptr_type}): {t.vec_type};")
            lines.append("var i: Integer;")
            lines.append("begin")
            lines.append(f"  for i := 0 to {t.lanes - 1} do")
            lines.append(f"    Result.{t.field_name}[i] := p[i];")
            lines.append("end;")
            lines.append("")

        elif sig == "store":
            lines.append(f"procedure {slot.scalar_name}(p: {t.ptr_type}; const a: {t.vec_type});")
            lines.append("var i: Integer;")
            lines.append("begin")
            lines.append(f"  for i := 0 to {t.lanes - 1} do")
            lines.append(f"    p[i] := a.{t.field_name}[i];")
            lines.append("end;")
            lines.append("")

        elif sig == "splat":
            lines.append(f"function {slot.scalar_name}(value: {t.scalar_type}): {t.vec_type};")
            lines.append("var i: Integer;")
            lines.append("begin")
            lines.append(f"  for i := 0 to {t.lanes - 1} do")
            lines.append(f"    Result.{t.field_name}[i] := value;")
            lines.append("end;")
            lines.append("")

        elif sig == "zero":
            lines.append(f"function {slot.scalar_name}: {t.vec_type};")
            lines.append("begin")
            lines.append(f"  FillChar(Result, SizeOf(Result), 0);")
            lines.append("end;")
            lines.append("")

    return "\n".join(lines) + "\n"


def generate_fillbase(registry: Registry) -> str:
    lines = [HEADER, "{ FillBaseDispatchTable assignments }", ""]
    for slot in registry.slots:
        lines.append(f"  aTable.{slot.dispatch_field} := @{slot.scalar_name};")
    return "\n".join(lines) + "\n"


def generate_facade_decl(registry: Registry) -> str:
    lines = [HEADER, "{ Public facade function declarations }", ""]
    for slot in registry.slots:
        t = slot.type_info
        sig = slot.op.signature
        doc = slot.op.doc
        if doc:
            lines.append(f"{{ {doc}: {t.name} }}")
        if sig == "binary":
            lines.append(
                f"function {slot.facade_name}(const a, b: {t.vec_type}): {t.vec_type}; inline;"
            )
        elif sig == "unary":
            lines.append(
                f"function {slot.facade_name}(const a: {t.vec_type}): {t.vec_type}; inline;"
            )
        elif sig == "compare":
            lines.append(
                f"function {slot.facade_name}(const a, b: {t.vec_type}): {t.mask_type}; inline;"
            )
        elif sig == "reduce":
            lines.append(
                f"function {slot.facade_name}(const a: {t.vec_type}): {t.scalar_type}; inline;"
            )
        elif sig == "shift":
            lines.append(
                f"function {slot.facade_name}(const a: {t.vec_type}; count: Integer): {t.vec_type}; inline;"
            )
        elif sig == "load":
            lines.append(
                f"function {slot.facade_name}(p: {t.ptr_type}): {t.vec_type}; inline;"
            )
        elif sig == "store":
            lines.append(
                f"procedure {slot.facade_name}(p: {t.ptr_type}; const a: {t.vec_type}); inline;"
            )
        elif sig == "splat":
            lines.append(
                f"function {slot.facade_name}(value: {t.scalar_type}): {t.vec_type}; inline;"
            )
        elif sig == "zero":
            lines.append(
                f"function {slot.facade_name}: {t.vec_type}; inline;"
            )
    return "\n".join(lines) + "\n"


def generate_facade_impl(registry: Registry) -> str:
    lines = [HEADER, "{ Public facade function implementations }", ""]
    for slot in registry.slots:
        t = slot.type_info
        sig = slot.op.signature

        if sig == "binary":
            lines.append(f"function {slot.facade_name}(const a, b: {t.vec_type}): {t.vec_type};")
            lines.append("var LDispatch: PSimdDispatchTable;")
            lines.append("begin")
            lines.append("  LDispatch := GetSimdFacadeDispatchFastPath;")
            lines.append(f"  Result := LDispatch^.{slot.dispatch_field}(a, b);")
            lines.append("end;")
            lines.append("")
        elif sig == "unary":
            lines.append(f"function {slot.facade_name}(const a: {t.vec_type}): {t.vec_type};")
            lines.append("var LDispatch: PSimdDispatchTable;")
            lines.append("begin")
            lines.append("  LDispatch := GetSimdFacadeDispatchFastPath;")
            lines.append(f"  Result := LDispatch^.{slot.dispatch_field}(a);")
            lines.append("end;")
            lines.append("")
        elif sig == "compare":
            lines.append(f"function {slot.facade_name}(const a, b: {t.vec_type}): {t.mask_type};")
            lines.append("var LDispatch: PSimdDispatchTable;")
            lines.append("begin")
            lines.append("  LDispatch := GetSimdFacadeDispatchFastPath;")
            lines.append(f"  Result := LDispatch^.{slot.dispatch_field}(a, b);")
            lines.append("end;")
            lines.append("")
        elif sig == "reduce":
            lines.append(f"function {slot.facade_name}(const a: {t.vec_type}): {t.scalar_type};")
            lines.append("var LDispatch: PSimdDispatchTable;")
            lines.append("begin")
            lines.append("  LDispatch := GetSimdFacadeDispatchFastPath;")
            lines.append(f"  Result := LDispatch^.{slot.dispatch_field}(a);")
            lines.append("end;")
            lines.append("")
        elif sig == "shift":
            lines.append(f"function {slot.facade_name}(const a: {t.vec_type}; count: Integer): {t.vec_type};")
            lines.append("var LDispatch: PSimdDispatchTable;")
            lines.append("begin")
            lines.append("  LDispatch := GetSimdFacadeDispatchFastPath;")
            lines.append(f"  Result := LDispatch^.{slot.dispatch_field}(a, count);")
            lines.append("end;")
            lines.append("")
        elif sig == "load":
            lines.append(f"function {slot.facade_name}(p: {t.ptr_type}): {t.vec_type};")
            lines.append("var LDispatch: PSimdDispatchTable;")
            lines.append("begin")
            lines.append("  LDispatch := GetSimdFacadeDispatchFastPath;")
            lines.append(f"  Result := LDispatch^.{slot.dispatch_field}(p);")
            lines.append("end;")
            lines.append("")
        elif sig == "store":
            lines.append(f"procedure {slot.facade_name}(p: {t.ptr_type}; const a: {t.vec_type});")
            lines.append("var LDispatch: PSimdDispatchTable;")
            lines.append("begin")
            lines.append("  LDispatch := GetSimdFacadeDispatchFastPath;")
            lines.append(f"  LDispatch^.{slot.dispatch_field}(p, a);")
            lines.append("end;")
            lines.append("")
        elif sig == "splat":
            lines.append(f"function {slot.facade_name}(value: {t.scalar_type}): {t.vec_type};")
            lines.append("var LDispatch: PSimdDispatchTable;")
            lines.append("begin")
            lines.append("  LDispatch := GetSimdFacadeDispatchFastPath;")
            lines.append(f"  Result := LDispatch^.{slot.dispatch_field}(value);")
            lines.append("end;")
            lines.append("")
        elif sig == "zero":
            lines.append(f"function {slot.facade_name}: {t.vec_type};")
            lines.append("var LDispatch: PSimdDispatchTable;")
            lines.append("begin")
            lines.append("  LDispatch := GetSimdFacadeDispatchFastPath;")
            lines.append(f"  Result := LDispatch^.{slot.dispatch_field};")
            lines.append("end;")
            lines.append("")

    return "\n".join(lines) + "\n"


# =============================================================================
# Audit: parse existing dispatch table and compare
# =============================================================================

import re

def parse_existing_dispatch_table(dispatch_path: Path) -> dict[str, str]:
    """Parse existing TSimdDispatchTable fields from dispatch.pas.
    Returns dict of {field_name: full_signature_line}"""
    slots = {}
    pattern = re.compile(r'^\s+(\w+):\s+(function|procedure)\s*(.+);', re.IGNORECASE)
    with open(dispatch_path) as f:
        in_record = False
        for line in f:
            if 'TSimdDispatchTable = record' in line:
                in_record = True
                continue
            if in_record and line.strip().startswith('end;'):
                break
            if in_record:
                m = pattern.match(line)
                if m:
                    field_name = m.group(1)
                    sig_type = m.group(2).lower()
                    sig_rest = m.group(3).strip()
                    slots[field_name] = f"{sig_type}{sig_rest}"
    return slots


def run_audit(registry: Registry):
    """Compare generated slots against existing dispatch table."""
    dispatch_path = PROJECT_ROOT / "src" / "fafafa.core.simd.dispatch.pas"
    if not dispatch_path.exists():
        print("[AUDIT] ERROR: dispatch.pas not found")
        return

    existing = parse_existing_dispatch_table(dispatch_path)
    generated = {}
    for slot in registry.slots:
        sig = gen_signature(slot)
        generated[slot.dispatch_field] = sig

    existing_names = set(existing.keys())
    generated_names = set(generated.keys())

    matched = existing_names & generated_names
    missing_from_gen = existing_names - generated_names
    extra_in_gen = generated_names - existing_names

    # Check signature compatibility for matched slots
    sig_matches = []
    sig_mismatches = []
    for name in sorted(matched):
        existing_sig = existing[name].rstrip(';').strip()
        gen_sig = generated[name].rstrip(';').strip()
        # Normalize for comparison
        e_norm = re.sub(r'\s+', ' ', existing_sig.lower())
        g_norm = re.sub(r'\s+', ' ', gen_sig.lower())
        if e_norm == g_norm:
            sig_matches.append(name)
        else:
            sig_mismatches.append((name, existing[name], generated[name]))

    # Print report
    print(f"\n{'='*70}")
    print(f"  SIMD DISPATCH TABLE AUDIT REPORT")
    print(f"{'='*70}")
    print(f"\n  Existing slots:  {len(existing_names)}")
    print(f"  Generated slots: {len(generated_names)}")
    print(f"  Matched:         {len(matched)} ({len(sig_matches)} compatible, {len(sig_mismatches)} mismatched)")
    print(f"  Missing (not in simdgen): {len(missing_from_gen)}")
    print(f"  Extra (in simdgen only):  {len(extra_in_gen)}")

    coverage_pct = len(matched) / len(existing_names) * 100 if existing_names else 0
    print(f"\n  Coverage: {coverage_pct:.1f}%")

    if sig_mismatches:
        print(f"\n  --- SIGNATURE MISMATCHES ({len(sig_mismatches)}) ---")
        for name, e_sig, g_sig in sig_mismatches[:20]:
            print(f"    {name}:")
            print(f"      existing:  {e_sig}")
            print(f"      generated: {g_sig}")

    if missing_from_gen:
        # Categorize missing slots
        categories: dict[str, list[str]] = {}
        for name in sorted(missing_from_gen):
            # Try to extract operation prefix
            op = re.sub(r'(F32x4|F32x8|F32x16|F64x2|F64x4|F64x8|I32x4|I32x8|I32x16|'
                       r'I64x2|I64x4|I64x8|U32x4|U32x8|U32x16|U64x2|U64x4|U64x8|'
                       r'I16x8|I16x32|I8x16|I8x64|U16x8|U8x16|U8x64|'
                       r'Mask2|Mask4|Mask8|Mask16|F32x3)$', '', name)
            if not op:
                op = name
            categories.setdefault(op, []).append(name)

        print(f"\n  --- MISSING FROM SIMDGEN ({len(missing_from_gen)}) ---")
        print(f"  (grouped by operation)")
        for op in sorted(categories.keys()):
            slots_list = categories[op]
            types_str = ', '.join(s.replace(op, '') for s in slots_list[:8])
            suffix = f" +{len(slots_list)-8} more" if len(slots_list) > 8 else ""
            print(f"    {op}: [{types_str}{suffix}]")

    if extra_in_gen:
        print(f"\n  --- EXTRA IN SIMDGEN (not in existing) ({len(extra_in_gen)}) ---")
        for name in sorted(extra_in_gen)[:20]:
            print(f"    {name}")

    print(f"\n{'='*70}")

    # Summary line for CI
    status = "OK" if not sig_mismatches and not extra_in_gen else "DRIFT"
    print(f"SIMDGEN_AUDIT existing={len(existing_names)} generated={len(generated_names)} "
          f"matched={len(matched)} compatible={len(sig_matches)} "
          f"mismatched={len(sig_mismatches)} missing={len(missing_from_gen)} "
          f"extra={len(extra_in_gen)} coverage={coverage_pct:.1f}% status={status}")


# =============================================================================
# Main
# =============================================================================

def main():
    verify_mode = "--verify" in sys.argv
    dry_run = "--dry-run" in sys.argv
    sort_by_type = "--sort-by-type" in sys.argv
    audit_mode = "--audit" in sys.argv

    registry = Registry()
    registry.load_all()

    if sort_by_type:
        registry.slots.sort(key=lambda s: (s.type_info.width, s.type_info.name, s.op.category))

    print(f"[simdgen] Loaded {len(registry.types)} types, "
          f"{len(registry.operations)} operations, "
          f"{len(registry.slots)} slots")

    if audit_mode:
        run_audit(registry)
        return

    generators = {
        "fafafa.core.simd.dispatch.slots.inc": generate_dispatch_slots,
        "fafafa.core.simd.scalar.decl.inc": generate_scalar_decl,
        "fafafa.core.simd.scalar.impl.inc": generate_scalar_impl,
        "fafafa.core.simd.fillbase.inc": generate_fillbase,
        "fafafa.core.simd.facade.decl.inc": generate_facade_decl,
        "fafafa.core.simd.facade.impl.inc": generate_facade_impl,
    }

    OUTPUT_DIR.mkdir(parents=True, exist_ok=True)

    for filename, gen_func in generators.items():
        content = gen_func(registry)
        output_path = OUTPUT_DIR / filename

        if dry_run:
            print(f"\n{'='*60}")
            print(f"  {filename} ({len(content.splitlines())} lines)")
            print(f"{'='*60}")
            print(content[:2000])
            if len(content) > 2000:
                print(f"  ... ({len(content)} chars total)")
            continue

        if verify_mode:
            if output_path.exists():
                existing = output_path.read_text()
                if existing == content:
                    print(f"  [OK] {filename}")
                else:
                    print(f"  [DRIFT] {filename} - generated differs from existing")
            else:
                print(f"  [NEW] {filename} - does not exist yet")
            continue

        output_path.write_text(content)
        print(f"  [WRITE] {filename} ({len(content.splitlines())} lines)")

    if not dry_run and not verify_mode:
        print(f"\n[simdgen] Generated {len(generators)} files in {OUTPUT_DIR}")


if __name__ == "__main__":
    main()
